### ISSUE TITLE
undefined method `Raw' for LinodeAPI:Module

### ISSUE THREAD

**Issue by iwada** [akerl/linodeapi#22]
Hi, Following the Readme, 
    
    api_one = LinodeAPI::Raw(apikey: 'YOUR_KEY_HERE')
produces 
      
     undefined method `Raw' for LinodeAPI:Module

Using Ruby 2.2.2

**Comment by akerl** [comment]
Whoops. That should be LinodeAPI::Raw.new(apikey: "")

Will fix the docs tonight, thanks for the heads up

**Comment by iwada** [comment]
Nay Problem.

**Comment by akerl** [comment]
Merged, thanks!
