### ISSUE TITLE
should follow up when Retry-After headers are present on 429 and 503s

### ISSUE THREAD

**Issue by displague** [akerl/linodeapi#25]
LinodeAPI should configurably (max-retries=0, max-retry-after=60) retry requests with HTTP status >= 400 when Retry-After is present.

This will take the onus off of clients so they won't have to dig into the HTTP response that LinodeAPI is intended to shield.

I use this to trigger 429s:

``` bash
apt-get install httpie
read -s -p Key:\  KEY
for ((i=0;i<60;i++)); do
 URL="https://api.linode.com/?api_action=user.getAPIKey&api_key=$KEY"
 http --headers GET $URL 2>&1 > /tmp/$i.log &  sleep .25;  
done
```

**Comment by akerl** [comment]
I've cut a few changes as part of this:

* Added actual errors that split up the various ways a request could fail: https://github.com/akerl/linodeapi/blob/master/lib/linodeapi/errors.rb
* Cleaned up a whole pile of crufty past-Les code in raw.rb
* Cut a brand new class, LinodeAPI::Retryable. It inherits LinodeAPI::Raw, takes max_retries / max_delay, and when you call requests on it, it works just like Raw except with retries on retryable errors.

**Comment by akerl** [comment]
I cut version 2.0.0 with these changes
