### ISSUE TITLE
Linode API authentication problem

### ISSUE THREAD

**Issue by cpanelrikus** [akerl/linodeapi#29]
## Summary

I encountered this problem while using `displague/vagrant-linode`, but it appears that the underlying issue may actually be with `akerl/linodeapi` version 2.0.3. The API client fails to authenticate to the API server.

I see at least two potential problems:

* Client code is embedding the API token in the request body rather than sending an `Authorization: Bearer XXXXXXXXXXXXX` type header. See: https://developers.linode.com/api/v4/#access-and-authentication
* Client code is hitting https://api.linode.com/ (top level) rather than some endpoint under `/v4/......`

Is `akerl/linodeapi` using an older version of the Linode API? The current version is 4.

## Steps to reproduce

1. Follow the setup steps described at https://www.linode.com/docs/applications/configuration-management/vagrant-linode-environments/ to install and configure the vagrant-linode plugin (I also tried fetching the vagrant-linode source from GitHub, building the gem locally, and installing it with --plugin-source set to pull the local copy; this made no difference)
1. Embed a working Personal Access Token in the Vagrantfile via environment variable
1. Run `vagrant up Linode` (In my case, Linode has its own config section)
1. See that the authentication fails

```
Bringing machine 'Linode' up with 'linode' provider...
--
==> Linode: Linode has not been created
==> Linode: [{"ERRORMESSAGE"=>"Authentication failed", "ERRORCODE"=>4}]
/root/.vagrant.d/gems/2.4.5/gems/linodeapi-2.0.3/lib/linodeapi/helpers.rb:23:in `parse': API Error encountered (LinodeAPI::APIError)
from /root/.vagrant.d/gems/2.4.5/gems/linodeapi-2.0.3/lib/linodeapi/helpers.rb:10:in `error_check'
from /root/.vagrant.d/gems/2.4.5/gems/linodeapi-2.0.3/lib/linodeapi/raw.rb:85:in `call'
```

Note that:

1. The request made by vagrant-linode is actually being built and sent by the linodeapi gem.
1. The version of the gem it's using is 2.0.3, which is also the latest release of linodeapi available on GitHub.

### Check that the Personal Access Token is actually working. It is:

```
# curl -qs -X GET -H "Authorization: Bearer $LINODE_TOKEN" 'https://api.linode.com/v4/linode/instances' | json_pp
{
   "data" : [],
   "page" : 1,
   "results" : 0,
   "pages" : 1
}
```

### Check how the request is being built

This POST request https://github.com/akerl/linodeapi/blob/8a00b61caf35d0fee6c07f83855fcd17c3f05b78/lib/linodeapi/raw.rb#L85

```
      options = build_call_body(method, params)
      self.class.error_check self.class.post(
        '', body: options,
            base_uri: endpoint,
            headers: { 'User-Agent' => user_agent }
      )
```

... appears to be embedding the API token (part of `options`) within the request body, and it does not appear to be adding the `Authorization: Bearer XXXXXXXXXXXXX` header.

I confirmed that `options` contains the correct `api_key` value by dumping out the contents with `pp`, but I don't think it's being sent correctly in the request.

I also notice that the endpoint being used is `https://api.linode.com/`, but this doesn't seem to work, even with a proper Bearer token:

```
# curl -qs -X POST -H "Authorization: Bearer $LINODE_TOKEN" https://api.linode.com/ | json_pp
{
   "ACTION" : "",
   "DATA" : {},
   "ERRORARRAY" : [
      {
         "ERRORMESSAGE" : "Authentication failed",
         "ERRORCODE" : 4
      }
   ]
}
```

```
# curl -qs -X POST https://api.linode.com/ | json_pp                                         
{
   "ACTION" : "",
   "DATA" : {},
   "ERRORARRAY" : [
      {
         "ERRORMESSAGE" : "Authentication failed",
         "ERRORCODE" : 4
      }
   ]
}
```

Notice that these curl-based requests to the same URL `akerl/linodeapi` is hitting are able to replicate the error, even when the bearer token that worked in a different (v4) request is supplied.

**Comment by akerl** [comment]
Yes, this gem uses the existing pre-v4 API. I’m not aware of a v4
replacement for the api.spec call, which is crucial for this gem moving to
v4

**Comment by cpanelrikus** [comment]
Thanks for confirming.

**Comment by cpanelrikus** [comment]
I went ahead and closed the issue since there may not be a real path forward right now. Feel free to reopen if needed.

**Comment by akerl** [comment]
For what it’s worth: I would love concerting to v4, so if there’s a way to
pull that info that I’m missing, that would rock.

**Comment by themetaschemer** [comment]
api.spec call does not seem to require any authentication any more. https://api.linode.com/?api_action=api.spec returns a complete json spec without requiring any auth. You should be able to just call it.

**Comment by akerl** [comment]
@themetaschemer that URL is the pre-v4 API, which is what this gem uses already (and it does so without authentication).

The newer API is at https://api.linode.com/v4 , which didn't have an equivalent for the api.spec call the last time I looked into this. It may now, I haven't checked in a while.

**Comment by themetaschemer** [comment]
They have an openAPI spec now (https://www.linode.com/docs/api/openapi.yaml), perhaps that may be a good substitute.
